### ISSUE TITLE
Question: using css utility libraries like tailwind and daisyUI (with svelte vitebook)

### ISSUE THREAD

**Issue by malcolmalex** [vitebook/vitebook#10]
Hello - really excited to try this out.

Is there any guidance on how to include libraries like tailwind and daisyUI? I seem to have trouble getting styles to show up in the component browser unless I add the CDNs to the HEAD using instructions here: 

https://vitebook.dev/introduction/configuration.html#site-head.

Otherwise, I sometimes get styles showing in the browser, and sometimes not, and I haven't been able to determine the pattern.

Is there a way to ensure the vite processing pulls these libraries in as appropriate, ideally with only the classes needed? I'm new to vite so digging into the vitebook code is slow going.

Thx.

**Comment by mihar-22** [comment]
👋  @malcolmalex excited you want to try it out. I've added a Tailwind example which you can find [here](https://github.com/vitebook/vitebook/tree/main/examples/tailwind). I've also added some steps to the `README` on how to get it up and running in your own project.

**Comment by mihar-22** [comment]
Let me know if you run into any issues.

**Comment by malcolmalex** [comment]
Thank you @mihar-22 for the quick response and full example! This helps a ton and I was able to get it working!
