### ISSUE TITLE
Pls add React Example

### ISSUE THREAD

**Issue by harrytran998** [vitebook/vitebook#11]
I tried to make a React app like your guide in Readme, but seemingly doesn't work. Hop your team can have at least one! Thank you for the awesome tools!

**Comment by mihar-22** [comment]
Done, I'll make one tomorrow 😄

**Comment by mihar-22** [comment]
👋  @harrytran998 

You can find a [React example](https://github.com/vitebook/vitebook/tree/main/examples/react) in the `examples` directory now as requested 🎉 

Let me know how you go, and feel free to raise a new issue if you run into any problems.
