### ISSUE TITLE
Vitebook Preact demo not working

### ISSUE THREAD

**Issue by dorinvancea** [vitebook/vitebook#13]
Hi! 

I tried loading the Vitebook Preact: https://stackblitz.com/github/vitebook/vitebook/tree/main/examples/preact
but unfortunately it returns an error: 
![Screenshot 2022-01-12 at 08 23 09](https://user-images.githubusercontent.com/5360865/149090705-ee8ae857-7892-4a3d-8866-b967a4e4539f.png)

Also: I was wondering if you could provide a basic demo that uses JS/JSX files, not just TSX.

Thanks!

**Comment by mihar-22** [comment]
Hey @dorinvancea, ye I'm aware of that issue with both Preact and Vue. Need to find a fix. If you press the refresh icon in the Stackblitz browser (not your actual browser), it'll work perfectly fine. This doesn't happen locally.

**Comment by mihar-22** [comment]
As soon as I have time I'll try to resolve it as it's quite annoying. Oh and sure I'll put together a Preact demo using JS/JSX 😄

**Comment by dorinvancea** [comment]
Thanks Mihar! 🚀

**Comment by mihar-22** [comment]
Demo is now fixed and JS example has been added. Enjoy 🍎
