### ISSUE TITLE
init / create vitebook my-app not working

### ISSUE THREAD

**Issue by kuechlerm** [vitebook/vitebook#20]
Hi, doing one of the following is not working:

- npm init vitebook my-app
- select Svelte / TS / Prettier / Tailwind
- cd my-app
- npm i
- npm run vitebook:dev
 
OR the same steps for pnpm

I get the following result and have no idea what to do.

Im on Win10, Node 16, current pnpm

```
error: The entry point "C:/Dev/tests/my-app/.vitebook/config.ts" cannot be marked as external

 Error: Build failed with 1 error:
error: The entry point "C:/Dev/tests/my-app/.vitebook/config.ts" cannot be marked as external
    at failureErrorWithLog (C:\Dev\tests\my-app\node_modules\esbuild\lib\main.js:1475:15)
    at C:\Dev\tests\my-app\node_modules\esbuild\lib\main.js:1133:28
    at runOnEndCallbacks (C:\Dev\tests\my-app\node_modules\esbuild\lib\main.js:923:63)
    at buildResponseToResult (C:\Dev\tests\my-app\node_modules\esbuild\lib\main.js:1131:7)
    at C:\Dev\tests/my-app\node_modules\esbuild\lib\main.js:1240:14
    at C:\Dev\tests/my-app\node_modules\esbuild\lib\main.js:611:9
    at handleIncomingPacket (C:\Dev\tests\my-app\node_modules\esbuild\lib\main.js:708:9)
    at Socket.readFromStdout (C:\Dev\tests\my-app\node_modules\esbuild\lib\main.js:578:7)
    at Socket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:315:12) {
  errors: [
    {
      detail: undefined,
      location: null,
      notes: [],
      pluginName: '',
      text: 'The entry point "C:/Dev/tests/my-app/.vitebook/config.ts" cannot be marked as external'
    }
  ],
  warnings: []
}
```

When I only pick Svelte without any options I get
```
error: The entry point "C:/Dev/tests/test-3/.vitebook/config.js" cannot be marked as external
```

**Comment by mihar-22** [comment]
I'd love to debug this @kuechlerm but I can't because I don't have a dev environment ready to go on a Windows machine. I'll try sometime this week to diagnose the issue blindly and come back if I have anything.

**Comment by JamesYeoman** [comment]
I use Yarn for my project, and I'm getting the exact same issue when trying to run `yarn vitebook:dev`

**Comment by JamesYeoman** [comment]
Following the data flow for [resolveApp.ts](https://github.com/vitebook/vitebook/blob/main/packages/core/src/node/app/resolveApp.ts), it looks like  the resolving gets delegated to the esbuild bundle, which [blindly marks files as external](https://github.com/vitebook/vitebook/blob/510bc031fd0423c95a2879bd4ada0ef5fed4bbbb/packages/core/src/node/utils/module.ts#L121). I'm not too familiar with the codebase here, so @mihar-22 do you have any ideas as to what should be done?

I find it hard to believe that the marking as external is windows-only, so there's got to be something further up the chain that is causing this to go crazy

**Comment by JamesYeoman** [comment]
One thing to note is that because I'm using Tauri as my backend, I've had to change my root folder for vite to be `/frontend`, and I've got `.vitebook` in `/` because vitebook seems to be hardcoded to look for `.vitebook` in `/`. I don't know what implications, if any, this would have, but [here's my repo](https://github.com/JamesYeoman/dsrbmm/tree/file_list) that I'm working on, just in case there _is_ something funky going on somewhere in the usage.

**Comment by mihar-22** [comment]
Unforunately I have no idea @JamesYeoman. I don't see why this would only happen on Windows, hard to debug blindly. The only thing I can guess is somehow this `const filter = /^[^.\/]|^\.[^.\/]|^\.\.[^\/]/;` fails on Windows and marks the entry file as external.

I wonder does this `C:/Dev/tests/my-app/.vitebook/config.ts` become this `/Dev/tests/my-app/.vitebook/config.ts` when ESBuild is resolving files?

As a test, try going straight into `node_modules/@vitebook/core/dist/cli/run.js` in your project and removing the filter to see how that goes.

**Comment by JamesYeoman** [comment]
When I straight-up remove the filter from the onResolve options object, I get this: 
![image](https://user-images.githubusercontent.com/21042602/152550736-d6e4cedc-8574-41b9-acce-a06ac67fbeba.png)

When I set the filter to `/^whywouldthismatchanything/`, I get this:
![image](https://user-images.githubusercontent.com/21042602/152550899-10885e18-fe8b-4ea8-b3ea-a821129b450a.png)

**Comment by CalebKester** [comment]
Not that I'm much help, but I tried to install vitebook on my windows machine and I'm getting the same error. I think that #51 is the same issue as well.

**Comment by medyll** [comment]
Hello, i'm a windows user and i've got the same issue, if knowing this can help

**Comment by mihar-22** [comment]
Unfortunately I don't have a Window's dev environment to debug this, I'd need someone who does to help out.

**Comment by medyll** [comment]
> 

how can i help you ? 
- node 16.14
- svelte 3.46
nothing fancy installed, almost a raw svelte app

**Comment by Myrmod** [comment]
> Unfortunately I don't have a Window's dev environment to debug this, I'd need someone who does to help out.

I can run #60 on my windows machine if this help. If you have time we can try to debug this together.
