### ISSUE TITLE
Document [1]first.md, [2]second.md

### ISSUE THREAD

**Issue by jacobbowdoin** [vitebook/vitebook#23]
How do we utilize the `[1]folder/[1]doc.md` naming scheme seen in Vitebook docs? I tried and end up with ugly "1 Introduction" titles.

**Comment by mihar-22** [comment]
It should work out of the box. Was the URL and sidebar fine but the heading messed up or? Adding a heading tag `# My Heading` to the markdown document should fix it.

**Comment by jacobbowdoin** [comment]
The URL is good and a heading is already only showing if I use a `# Heading`, but it's the sidebar that's wonky: 
![image](https://user-images.githubusercontent.com/7559478/151937299-1b8ae2df-eabe-4dc9-a8a8-75e32a622ebf.png)

**Comment by mihar-22** [comment]
Hm, that's odd. It shouldn't be doing that. Can you share a simple repo or just your Vitebook config and directory structure so I can repro.
