### ISSUE TITLE
SvelteKit example breaks with pnmp

### ISSUE THREAD

**Issue by macmillen** [vitebook/vitebook#25]
Unfortunately the SvelteKit example doesn't work when installing the dependencies with `pnpm i`. There seems to be an issue where the dependencies don't get detected.

When I install the dependencies manually I get different errors for other dependencies. See below:

First Error
```
 Error: 🚨 @vitebook/client requires @sveltejs/vite-plugin-svelte
```

Second Error
```
 Error: Failed to resolve force included dependency: just-throttle
```

Third Error
```
 Error: Failed to resolve force included dependency: just-debounce-it
```

**Comment by dominikg** [comment]
as a workaround you can do `pnpm i -D @sveltejs/vite-plugin-svelte just-throttle just-debounce-it` 
or set `shamefully-hoist = true` in .npmrc

both of which are not ideal, but at least it works until this issue is resolved in a better way.

**Comment by bluwy** [comment]
Might be an issue within vitebook not taking into account of pnpm's strict installation 🤔 

(Doesn't work if `@sveltejs/vite-plugin-svelte` isn't installed in the project)
https://github.com/vitebook/vitebook/blob/c971e78acbf0e6397d5db306a945f06e9c3d31f6/packages/client/src/node/plugin.ts#L109-L111


(This line assumed that the user installed `just-throttle`, `just-debounce-it` in the project)
https://github.com/vitebook/vitebook/blob/c971e78acbf0e6397d5db306a945f06e9c3d31f6/packages/client/src/node/plugin.ts#L147

**Comment by dominikg** [comment]
thanks for digging into this!

For the just libraries, i don't think optimizeDeps is needed. they are typically only a single file and distributed as dual cjs/esm package. 
see https://github.com/angus-c/just/tree/master/packages/function-throttle for example.

**Comment by mihar-22** [comment]
Fixed! Also added SvelteKit detection to the `create` package so you don't need to configure anything manually anymore.
