### ISSUE TITLE
[SvelteKit] Failed to resolve `$app` 

### ISSUE THREAD

**Issue by macmillen** [vitebook/vitebook#26]
Vitebook can't resolve the `$app` path in SvelteKit projects.

```
Failed to resolve import "$app/env" from "src/lib/stores/storage.ts". Does the file exist?
1  |  import { browser } from "$app/env";
```

I guess this folder is not available in Vitebook since it is located at `.svelte-kit/dev/runtime/app` which is not being generated by Vitebook. Is there a way to workaround it or to mock this?

**Comment by mihar-22** [comment]
The latest `create` package detects svelte kits and sets the aliases. Add [this line](https://github.com/vitebook/vitebook/blob/main/examples/svelte-kit/.vitebook/config.ts#L13) to your config and it should work 😄

**Comment by macmillen** [comment]
@mihar-22 This is still an issue when I try to vitebook:build. I think it's because `/.svelte-kit/runtime/app/env` doesn't exist before running the dev server of SvelteKit.

```
16:05:29.875 | > vitebook:build
16:05:29.875 | > vitebook build
16:05:29.875 |  
16:05:30.353 | vitebook@0.20.1
16:05:30.353 |  
16:05:30.354 | - Resolving pages...
16:05:30.369 | - Rendering 3 pages...
16:05:36.988 | [vite:load-fallback] Could not load /.svelte-kit/runtime/app/env (imported by src/lib/stores/storage.ts): ENOENT: no such file or directory, open '/.svelte-kit/runtime/app/env'
16:05:36.989 | 🚨 Rendering 3 pages...
16:05:36.992 |  
16:05:36.992 | [Error: Could not load /.svelte-kit/runtime/app/env (imported by src/lib/stores/storage.ts): ENOENT: no such file or directory, open '/.svelte-kit/runtime/app/env'] {
16:05:36.992 | errno: -2,
16:05:36.992 | code: 'PLUGIN_ERROR',
16:05:36.992 | syscall: 'open',
16:05:36.992 | path: '/.svelte-kit/runtime/app/env',
16:05:36.992 | pluginCode: 'ENOENT',
16:05:36.992 | plugin: 'vite:load-fallback',
16:05:36.992 | hook: 'load',
16:05:36.992 | watchFiles: [


```

**Comment by jacobbowdoin** [comment]
In response to @mihar-22 query as to a good recommendation on a path to solve this, I don't know of an easy path, but https://github.com/sveltejs/kit/issues/1485 is probably the best place to start looking for solutions. From that and linked threads it looks like this will be addressed post Svelte-Kit 1.0. As I see it the two easiest to implement options for now are:

1) As much as possible design applications such that the page level route components fetch svelte-kit parameters and then pass props directly into the smaller components. That avoids this whole problem and is probably a better flow for testing in general but it's kind of painful sometimes to have to pass props down when they available globally through simple import.

2) Create shims, here's one for example called `/sk-shims/app/env.js`:
```js
const amp = false;
const browser = false;
const dev = true;
const mode = 'test';
export { amp, browser, dev, mode };
```
Then in `config.ts` use `alias: { $app: '/sk-shims/app' }`

See the issue referenced above for more shimming ideas if needed -  https://github.com/sveltejs/kit/issues/1485#issuecomment-920923252 is perhaps a good place to start.

**Comment by mihar-22** [comment]
Fixed by aliasing directly inside `@sveltejs/kit`, update the `$app` alias as shown [here](https://github.com/vitebook/vitebook/blob/main/examples/svelte-kit/.vitebook/config.ts#L13).

**Comment by dominikg-lakatu** [comment]
fyi, in older versions of sveltekit you might have to use`$app: '/node_modules/@sveltejs/kit/assets/runtime/app'`

**Comment by dominikg** [comment]
fyi, in older versions of sveltekit (1.0.0-next.223 in my case) this works `$app: '/node_modules/@sveltejs/kit/assets/runtime/app',`
