### ISSUE TITLE
Controls Addons

### ISSUE THREAD

**Issue by mihar-22** [vitebook/vitebook#3]
## Requirements

- [x] #2 

## Background

This is still in the initial design phase. First step is figuring out what API would be most developer friendly between wire it up yourself vs. Vitebook wiring it up.

To keep it super simple, since Vitebook stories are just framework components, maybe something like this could work...

_Svelte example_

```svelte
<script>
import Textfield from './TextField.svelte';
import { ControlsAddon } from '@vitebook/client/addons/controls';

let props = {
  title: '',
  active: false,
};
</script>

<TextField {...props} />

<!-- Anything inside of here will be teleported (aka "portal") inside the controls addon section -->
<ControlsAddon>
  <input type="text" bind:value={props.title} />
  <input type="checkbox" bind:value={props.active} />
</ControlsAddon>
```

**Comment by mariusheine** [comment]
This could also allow to keep the controls and the internal component state in sync, e.g. where I can change the selected image of a gallery by interacting with the displayed component or via the controls

```
<Gallery v-model="selectedImage" images="images" />

<ControlsAddon>
  <input type="number" v-model="selectedImage" />
</ControlsAddon>
```

I had those situations quite a few times and this is currently not possible with storybook.

**Comment by mihar-22** [comment]
About to release this 😄  Docs and examples coming right after.
