### ISSUE TITLE
[SvelteKit] js error in build

### ISSUE THREAD

**Issue by el-sonny** [vitebook/vitebook#30]
Hi, 
Ran into an issue when trying to make a vitebook build with sveltekit

```bash
npm run vitebook:build
npm run vitebook:preview
```

serves a build that gives a js error:

`Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'classList')
`

This can be reproduced in the official [svetelkit example](https://stackblitz.com/github/vitebook/vitebook/tree/main/examples/)
 
by running the build and preview commands.

Thanks in advance for any help

**Comment by mihar-22** [comment]
`hydratable` compiler option was missing, add [this](https://github.com/vitebook/vitebook/blob/main/examples/svelte/.vitebook/config.ts#L18-L20) to your config to resolve. Let me know if issue persists.

**Comment by el-sonny** [comment]
Thanks so much, solution worked.
