### ISSUE TITLE
Requiring Node >=15 breaks Vercel deployments

### ISSUE THREAD

**Issue by jacobbowdoin** [vitebook/vitebook#31]
FYI that AWS Lambda is a little slow to jump to Node 16 so anyone deploying anything to an environment utilizing Lambda (Vercel in my case: https://github.com/vercel/community/discussions/37) can't add @vitebook-core to their package.json. Is Node 16 really needed or can you downgrade the minimum to v14? https://github.com/vitebook/vitebook/blob/f9fdafe97aeb96d94e4f6d2cef74c8875f0bee2e/packages/core/package.json#L92

Vercel build error:
![image](https://user-images.githubusercontent.com/7559478/152620098-38a69535-5e61-43fd-970b-1b52bcb20de0.png)

**Comment by mihar-22** [comment]
Looks like it's coming in the next 90 days, but until then I'll need to double check why `16` was required (I forgot to write it down 😓 ). I think it was mainly related to `esbuild` installation.

**Comment by jacobbowdoin** [comment]
Ok, my workaround until then is to deploy Vitebook to Netlify (node 16) and then for my regular Vercel production app I just modified the required engine in package-lock.json to "node": ">=14" for the time being to allow the build to work.
