### ISSUE TITLE
Sidebar not showing on deployed version

### ISSUE THREAD

**Issue by macmillen** [vitebook/vitebook#32]
In `vitebook:dev` mode it works fine but the deployed version with `vitebook:build` it shows an error + the sidebar is not showing. There is also a css media query that makes it invisible.

![image](https://user-images.githubusercontent.com/33156526/152682210-fc205978-e7a6-456a-930d-5e0dde33e62a.png)

**Comment by mihar-22** [comment]
Looking into it now 👍

**Comment by mihar-22** [comment]
`hydratable` compiler option was missing, add [this](https://github.com/vitebook/vitebook/blob/main/examples/svelte/.vitebook/config.ts#L18-L20) to your config to resolve. Let me know if issue persists.
