### ISSUE TITLE
Make the page__container flow vertically not horizontally

### ISSUE THREAD

**Issue by jacobbowdoin** [vitebook/vitebook#34]
Can you consider adding `flex-direction: column` to https://github.com/vitebook/vitebook/blob/main/packages/theme-default/src/client/layout/Page.svelte#L60-L64 so content doesn't always flow off to the sides w/o either a div wrapper or custom css?

Currently:
<img width="927" alt="image" src="https://user-images.githubusercontent.com/7559478/152968953-0ad095bd-fdb0-4877-a44a-3bc3fff3a20b.png">

With `flex-direction: column`:
<img width="871" alt="image" src="https://user-images.githubusercontent.com/7559478/152969053-baaa614f-ef86-476f-9772-df38055e876c.png">

_(Yes, I upgraded TW and my white is not white...)_

**Comment by mihar-22** [comment]
Released in `0.21.3`!
