### ISSUE TITLE
Error in exist vite vue project 'TypeError: App.configureApp is not a function'

### ISSUE THREAD

**Issue by wildwind123** [vitebook/vitebook#37]
Hello i am new user. Is it bag ?
reproduce
![image](https://user-images.githubusercontent.com/34130873/154395512-1caf300a-6657-43d8-9c56-8445f01cd9c3.png)
![image](https://user-images.githubusercontent.com/34130873/154395569-ef7aa82a-3a7d-4a3e-a941-f5ef9a386670.png)
![image](https://user-images.githubusercontent.com/34130873/154395650-4c7cca38-0f30-4b01-afd5-7a572bc27ad5.png)
![image](https://user-images.githubusercontent.com/34130873/154395701-23306bea-dea7-4cee-9dae-f50d91b1d612.png)

npm run vitebook:dev
![image](https://user-images.githubusercontent.com/34130873/154395742-dd07a521-0cef-405b-a98a-c10dac96b132.png)

If i install first
npm init vitebook
npm install
work fine

**Comment by mihar-22** [comment]
Fixed in `0.23.0` 🎉
