### ISSUE TITLE
Adding plugins: [vue()] to my vite.config.ts causes "TypeError: App.configureApp is not a function"

### ISSUE THREAD

**Issue by OwenVey** [vitebook/vitebook#39]
I started with a new minimal Vue 3 Vite project and added Vitebook but was only able to get it to work when removing `plugins: [vue()]`  from my `vite.config.ts`. This works fine until I try to build my library. Is there any way around this?

**Comment by mihar-22** [comment]
Fixed in `0.23.0` 🎉
