### ISSUE TITLE
Sidebar items not sorted

### ISSUE THREAD

**Issue by mikenikles** [vitebook/vitebook#43]
Hi :wave:,

Incredible work with this project! I started to use it an hour ago and have my project's documentation almost ready for deployment :heart_eyes:!

I follow [example 4](https://vitebook.dev/default-theme/configuration.html#example-4) to order my sidebar items. Unfortunately, the sidebar categories & items are alphabetically sorted, ignoring my `[1]` naming convention.

![image](https://user-images.githubusercontent.com/788827/155864752-ac660c70-b5fb-4d15-b8f3-1c7bf32109db.png)

![image](https://user-images.githubusercontent.com/788827/155864758-87d15d49-1dde-49a3-a31e-c691ab8fbbbf.png)

It's an easy fix just above [this line](https://github.com/vitebook/vitebook/blob/main/packages/theme-default/src/client/components/sidebar/autoSidebarItems.ts#L42), by adding the following sort statement:

```js
pages.sort((a, b) => a.rootPath < b.rootPath ? -1 : 1);
```

Let me know if you're ok with that fix and I'll open a PR for it.

Cheers,

Mike

**Comment by mihar-22** [comment]
Thanks for the feedback @mikenikles 😄  I can't fix it at that specific line because the pages are sorted server-side and sometimes custom routes can be passed in which is only detected on the server. I messed this up when I added support for custom routes. Fixed now in `0.23.2`!

**Comment by mikenikles** [comment]
I'm not familiar enough with the project source yet, but that makes sense. Thanks for the quick fix!
