### ISSUE TITLE
Events Addon

### ISSUE THREAD

**Issue by mihar-22** [vitebook/vitebook#5]
## Requirements

- [x] #2 

## Background

Haven't thought about this too much yet, but the idea is very loosely similar to [Storybook Actions](https://storybook.js.org/docs/react/essentials/actions). It'd be much simpler to forward the event logs to the browser's console instead of dealing with static object snapshots in an addon. Hmmmm.... ❓ I guess the problem is that it'd clog up the console, maybe an addon where you can simply turn on/off certain events and anything checked will be forwarded 🤔

**Comment by HoraceKeung** [comment]
When we develop a design system using Storybook, we will host the site and share the URL to the components. The Designer/Product Owner/Tester will then review them and we do not expect them to use the browser's console to check for events.

The Storybook Actions tab is useful as it is within the site (without the need to bring up browser console) so anyone can easily use it. And the events listed in the action tab only belongs to that specific component so it is a lot clearer compared to reading the browser console where it can also contain other console logs.

**Comment by mihar-22** [comment]
Agreed @HoraceKeung. I guess when I wrote my initial thoughts I was thinking of something simply for debugging, but the real advantage of tools like Storybook are that they're used as a communication tool, between technical and sometimes non-technical team members. 

Maybe there's a sweet middle ground between both ideas. We can hold a reference to the original event, show a static snapshot in the events addon panel, and we can also show a button that will forward the stored reference of the clicked event to the browser console for deeper inspection.

**Comment by mihar-22** [comment]
About to release this 😄 Docs and examples coming right after.
