### ISSUE TITLE
Vue + Markdown example not working

### ISSUE THREAD

**Issue by louwers** [vitebook/vitebook#64]
```
npm init vitebook vitebook
```
Select Vue & Markdown.

```
npm install
echo "# Hello World" > src/test.md
npm run vitebook:dev
```

The Markdown file will not show up.

**Comment by possan** [comment]
I get the same issue for the svelte example too, i get an empty vitebook default theme page with no menu, it seems like it loads correctly, it redirects to the default example component, but it never shows it.

```
npm init vitebook my-vitebook-test-app -- --template svelte
cd my-vitebook-test-app
npm i
npm run vitebook:dev
```

I also get the same behaviour on an previously perfectly working vitebook page so i suspect some (peer?) dependency somewhere was bumped and broke it.

Worth noting is that running `npm run vitebook:build && npm run vitebook:preview` works fine and builds a working page.

**Comment by possan** [comment]
After too many hours of attempts to debug why i got a blank screen i tried to downgrade some dependencies and found that  it works fine by just "downgrading" to an explicit dependency on vite `2.8.4` but not with newer ones.

**Comment by GZLiew** [comment]
@possan I facing the same issue with react, you downgrade vite to 2.8.4?

**Comment by henriquehbr** [comment]
@possan Might be related to #72, as both are very recent problems, and one might lead to the other, i suggest that we focus efforts there to address this issue, and close this one (and other similar issues) once it's solved

**Comment by mihar-22** [comment]
I finally found some time to fix it all and also finished upgrading to Vite 3 :) Everything should be working in latest, feel free to give it a try and let me know how you go. Raise a new issue if there's any problems.
