### ISSUE TITLE
Svelte & SvelteKit playgrounds are no longer working

### ISSUE THREAD

**Issue by sserdyuk** [vitebook/vitebook#71]
At some recent point both Svelte and SvelteKit playgrounds stopped working. The only thing that's rendered is the Vitebook logo. 

[Svelte](https://stackblitz.com/github/vitebook/vitebook/tree/main/examples/svelte)
[SvelteKit](https://stackblitz.com/github/vitebook/vitebook/tree/main/examples/svelte-kit)

![image](https://user-images.githubusercontent.com/395998/162031862-d1476106-5ce5-44ba-8ebf-01bd39ff1619.png)

**Comment by henriquehbr** [comment]
@sserdyuk Might be related to #72, as both are very recent problems, and one might lead to the other

Looking from your screenshot, it looks very similar to the same problem i'm having (which is the one mentioned on the issue above), where vitebook doesn't starts, but only it's logo is visible

**Comment by Myrmod** [comment]
The error message originates from  `vite/packages/vite/src/node/server/sourcemap.ts:59` and is caused in line 45

```js
const missingSources: string[] = []
  map.sourcesContent = await Promise.all(
    map.sources.map((sourcePath) => {
      if (sourcePath && !virtualSourceRE.test(sourcePath)) {
        sourcePath = decodeURI(sourcePath)
        if (sourceRoot) {
          sourcePath = path.resolve(sourceRoot, sourcePath)
        }
        return fs.readFile(sourcePath, 'utf-8').catch(() => {  //  here we have the file system error
          if (maybeVirtualHtmlSet.has(normalizePath(sourcePath))) return null
          missingSources.push(sourcePath)
          return null
        })
      }
      return null
    })
  )
```

**Comment by SarcevicAntonio** [comment]
stuck on this as well. tried getting it to work locally but ended up only with the logo and some white bars at the top and bottom.

**Comment by henriquehbr** [comment]
@SarcevicAntonio in the meantime you can use the solution proposed [here](https://github.com/vitebook/vitebook/issues/72#issuecomment-1092917089), honestly, comments like this are not helpful at all

**Comment by SarcevicAntonio** [comment]
I'm truly sorry. I should have worded it differently, since I didn't mean to offend, but show interest in this project.

**Comment by tomgrice** [comment]
Seems to still work for me if I run a `npm run vitebook:build` then use `npm run vitebook:preview`

It is inconvenient as hotreloading is not available, but a workaround nonetheless.

**Comment by iva2k** [comment]
It looks like vite@2.8.6 is the last working version.

I was able to revive the examples in Stackblitz (I tried a few) with pinning vite-plugin-svelte (if present) and vite package versions in package.json:

```jsonc
// package.json
{
  ...
  "devDependencies": {
+    "@sveltejs/vite-plugin-svelte": "1.0.0-next.36", // Only if it's used
       ...
+    "vite": "2.8.6"
  },
+  "pnpm": {
+    "overrides" : {
+      "@sveltejs/vite-plugin-svelte": "1.0.0-next.36",
+      "vite": "2.8.6"
+    }
+  },
  ...
}
```

I suggest using pnpm.overrides, but I got Stackblitz working without it.

**Comment by mihar-22** [comment]
I finally found some time to fix it all and also finished upgrading to Vite 3 :) Everything should be working in latest, feel free to give it a try and let me know how you go. Raise a new issue if there's any problems.
