### ISSUE TITLE
Broken since 0.18.6

### ISSUE THREAD

**Issue by GZLiew** [vitebook/vitebook#72]
HI this is a great idea so far 

Im facing an issue where nothing works anymore after updating to 0.19.0 and beyond

I even tried the same changes for your documentation site and it shows that it wasnt working

This library has alot of potential to be better than storybook...

reproducible link: https://stackblitz.com/edit/github-fxdhdg?file=package.json 
if you update to 0.19.0 and after the pages wont show anymore

**Comment by Myrmod** [comment]
If you're talking about the missing source files error I got the same kind of issue, but with other versions:

```
git clone https://github.com/Myrmod/svelte-babylon.git
cd svelte-babylon
# until here everthing works
npm i -d vite # at the time of writing going from vite 2.7.0 to vite 2.9.2
npm run vitebook:dev
```

Error message:
`Sourcemap for "/home/user/Projects/svelte-babylon/library/node_modules/@vitebook/client/dist/client/addons/events/EventsAddon.svelte" points to missing source files`

My vitebook versions are `^0.23.4`, so I assume, that the error originates from `vite`.

There have been similar reports:
- https://github.com/vitejs/vite/issues/5438
- https://github.com/sveltejs/kit/discussions/4551

**Comment by GZLiew** [comment]
@Myrmod hmm I still think the issue is caused by vitebook rather than vite. Since im able to run vite at `2.9.1` with vitebook `0.18.6`

**Comment by Myrmod** [comment]
Must be a combination of the two then. Tricky stuff

**Comment by henriquehbr** [comment]
Thanks for reporting this @GZLiew, i'm facing the same issue, tried downgrading vitebook to `0.18.6` as a temporary workaround, couldn't get it to work, but i think it's due to a completely unrelated reason:

```
4:50:50 AM [vite] Internal server error: /home/hbr/repos/github/itatiaia-portal-web/node_modules/@vitebook/client/dist/client/App.svelte:29:16 Cannot have an {:else} block outside an {#if ...} or {#each ...} block
  Plugin: vite-plugin-svelte
  File: /home/hbr/repos/github/itatiaia-portal-web/node_modules/@vitebook/client/dist/client/App.svelte
   27 |  const file = "node_modules/@vitebook/client/dist/client/App.svelte";
   28 |
   29 |  // (17:0) {:else}
                         ^
   30 |  function create_else_block(ctx) {
   31 |    let switch_instance;
```

I'm also using the exact vite version of you (`2.9.1`)

**Comment by joseaquino** [comment]
I've confirmed that the issue is with Vite `2.9.1` to get things working I recommend anchoring your Vite version to `2.8.6` which is the last working version for Vitebook

**Comment by GZLiew** [comment]
@joseaquino nope still doesnt work for me can you share me a sample repo? 

I tested it by bumping vite to `2.8.6` in their example stackblitz https://stackblitz.com/edit/github-woo8jb?file=package.json

**Comment by GZLiew** [comment]
@joseaquino you're right! 👍🏻  hard fixing the dependencies of vite to `2.8.6` does fixes the solution. Guys Im going to mark this as the solution until vite solves the problem for us.

**Comment by CM-IV** [comment]
The issue still persists for me with Vite@2.9.8.

Vite@2.8.6 working well, I'm running Vitebook with Vitest and testing my components by using the preact testing library.

**Comment by iva2k** [comment]
It looks like vite@2.8.6 is the last working version

I was able to revive the examples (I tried `examples/svelte-kit`) with pinning vite-plugin-svelte and vite package versions in package.json:

```jsonc
// package.json
{
  ...
  "devDependencies": {
+    "@sveltejs/vite-plugin-svelte": "1.0.0-next.36",
       ...
+    "vite": "2.8.6"
  },
+  "pnpm": {
+    "overrides" : {
+      "@sveltejs/vite-plugin-svelte": "1.0.0-next.36",
+      "vite": "2.8.6"
+    }
+  },
  ...
}
```

**Comment by mihar-22** [comment]
I finally found some time to fix it all and also finished upgrading to Vite 3 :) Everything should be working in latest, feel free to give it a try and let me know how you go. Raise a new issue if there's any problems.
