### ISSUE TITLE
Vitebook Update

### ISSUE THREAD

**Issue by mihar-22** [vitebook/vitebook#80]
I haven't been working on Vitebook due to other time commitments and I don't need a playground just yet (will need one soon). I was about to declare the end of Vitebook the other day but I'm re-thinking it now since I heard Storybook deprecated all unofficial formats as they're only supporting CSF format. This means you can't write stores in Svelte/Vue anymore. I already hate the CSF format and for template-based frameworks (Vue/Svelte) it just sucks even more.

I need to spend time revising Vitebook and thinking about how to make it more maintainable. Possible solutions for now are either we split Vitebook up into smaller parts (e.g., SSG/Stories), or we consolidate packages and just clean stuff up (e.g., collapse framework and markdown packages into one). 

The design needs to be completely revised, I hate it. I can do 100x better. It's just all over the place, probably as the result of Vitebook attempting to be an SSG, documentation tool, and Storybook alternative. Makes it really confusing.

Not promising what I'll do next, still thinking and processing what to do here. Any ideas/thoughts are appreciated. Feel free to share radical ideas. I'd love to here what a GOOD Storybook alterantive looks like to you. 

---

My other option is to just focus on Svelte and work with the community to build something that integrates directly with SvelteKit. @stolinski is working on [BooKit](https://github.com/leveluptuts/bookit) right now which does exactly that. Super early but he's making dope progress. SvelteKit specific tools make life so much easier. I released [KitDocs](https://github.com/svelteness/kit-docs) this week as a docs tool mainly for the Svelte community. Stripping away application-level complexity really helps.

**Comment by Myrmod** [comment]
I'd suggest you either focus on kit-docs or vitebook. For me they both have the same use case - to document something.

**Comment by chrisbbreuer** [comment]
I love the idea of a native integration into doc frameworks, like KitDocs or VitePress. 

IMO, creating "web components" out of this could be an interesting idea as well. This would allow the project to become incredibly flexible by allowing for simple/native integrations into, virtually, any doc framework. The custom element could also come with an "expand icon" that onClick could show a modal of an "expanded view".

**Comment by stolinski** [comment]
@bluwy Give Bookit a look. I'll have iframe isolation this week and progress has been fast. Also it's all Svelte Kit so it's a lot of fun to work on.

**Comment by bartenra** [comment]
Maybe building on top of [vite-plugin-ssr](https://vite-plugin-ssr.com/) is an option?

**Comment by mihar-22** [comment]
https://github.com/vitebook/vitebook/issues/81
