### ISSUE TITLE
Vitebook Next

### ISSUE THREAD

**Issue by mihar-22** [vitebook/vitebook#81]
Working on new version (experimental). [Tweeted about it](https://twitter.com/mihar_22/status/1524201462024138752) and I'll add more information on changes here. Definitely still figuring stuff out but I really want a simple SSG that comes with a sweet documentation and storybook-like theme out of the box which is lightweight and optional. I conflated these in the first version of Vitebook so I'm exploring a different take.

This will also give me a chance to go through the [Vitebook Feedback](https://github.com/vitebook/vitebook/issues/36) list and see how to best solve some of those challenges.

Changes will happen on the `next` branch and released on the `@next` dist-tag.

**Comment by mosheduminer** [comment]
Does this allow for any vite based configuration to work with vitebook? I'm asking because that would make it trivial to support solidjs (https://github.com/vitebook/vitebook/discussions/78).

Also, what does this mean for support for storybook stories?

**Comment by mihar-22** [comment]
> Does this allow for any vite based configuration to work with vitebook? I'm asking because that would make it trivial to support solidjs (https://github.com/vitebook/vitebook/discussions/78).

I don't think it's possible for any Vite config to auto-magically work because components have to be mounted, rendered, unmounted and so on. There has to be adapters for specific libraries. The good news is that the new architecture core is built to be library agnostic, so we just have to follow the structure of the Svelte package for other libraries. It should be mostly trivial.

> Also, what does this mean for support for storybook stories?

Stories are an important aspect of documentation and will still be supported, hope to just do it better (stuff like iframes instead of scoping). Stories will be provided through a separate package called `@vitebook/stories`.

**Comment by azat-io** [comment]
Same question about React

**Comment by theoephraim** [comment]
Hi @mihar-22!

Stumbled across this project while looking for a lighter alternative to storybook for a new project. It looks great :)

But it seems like there has been a bit of a lull in development, issues, etc...
Totally understand, but just curious if you're still working on this (or have plans to) before I invest some time and start using it.

Thanks!

**Comment by mihar-22** [comment]
Hey @theoephraim! Appreciate the understanding. I've actually finished the new version of Vitebook which just needs docs (time consuming) and it's taking a while because my plate is full. I still need to build the new Storybook theme and figure out how that will fit in too. I really want to get it out ASAP but other stuff is just higher priority for me at the moment. 

I can't give you an exact timeline but I'll definitely continue working on this once I get past some other stuff. I wouldn't recommend using Vitebook at the moment because it's broken due to upstream changes in Vite, so you might need to stick it out with Storybook for a little whille longer. 

+ Sorry for all the delays to any future readers.

**Comment by mihar-22** [comment]
I just wanted to add that I got it working again today and upgraded to Vite 3 (latest). Feel free to give it a try and see how it goes @theoephraim.

**Comment by theoephraim** [comment]
Thanks for the update! I totally understand. It takes so much extra effort to go from something that kind of works to something that's ready to be published...

I will definitely take a look, and am excited to see where this project goes!

In the meantime until things here are a bit more ready for primetime, I discovered https://histoire.dev/ which seems to be pretty good for vue-based projects like mine.

**Comment by mihar-22** [comment]
Yep! In the next version I'll be investigating using iframes. My original reason for not using it was just to avoid some development complexity in Vitebook but I think it'll be fine

**Comment by mihar-22** [comment]
--> https://github.com/vitebook/vitebook/discussions/99
